version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
  backend: &backend
    <<: *app
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/capstone2_development
    volumes:
      - ..:/workspace:cached
    ports:
      - 3000
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - 5432
volumes:
  postgres_data: